### ISSUE TITLE
API Coverage Roadmap

### ISSUE THREAD

**Issue by Archasion** [Archasion/robolt#3]
### API Endpoints
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #12
- [x] #16
- [x] #18
- [x] #19
- [x] #22
- [ ] #24
- [ ] Development API
- [ ] Followings API
- [ ] Game Internalization API
- [ ] Games API
- [ ] Groups API
- [ ] Inventory API
- [ ] Private Messages API
- [ ] Search API
- [ ] Trading API

### Other
- [x] Authenticate session with cookie
- [x] Clear session
